comments

diff --git a/configs/home/bashrc b/configs/home/bashrc
--- a/configs/home/bashrc
+++ b/configs/home/bashrc
@@ -123,10 +123,14 @@ fi
 #############################
 #        custom  ps1        #
 #############################
-PROMPT_COMMAND=__mkps1
+PROMPT_COMMAND=__mkps1 #needed for some reason
 __mkps1() {
+  #get return status of previous cmd 
   local EXIT_CODE="$?"
+  #create empty $PS1
   PS1=""
+
+  #define colors
   local BG_GRAY=`tput setab 240`
   local white=`tput setaf 7`
   local yellow=`tput setaf 221`
@@ -140,27 +144,35 @@ __mkps1() {
   local timeStamp="$(date +%I:%M%P)"
   local prompt_color=""
 
+  #makes the prompt symbol red if bad return code 
   if [ ${EXIT_CODE} != 0 ]; then
     prompt_color="${red}"
   fi
   
-  local term_width=$((`tput cols`-1))
-  local pre_line="    00:00xx  ${HOSTNAME}@${USER}  --> "
-  local pre_len=${#pre_line}
+  #get current dir
   local curDir="$(pwd)"
+  #check if dir is within $HOME
   if [[ "${curDir}" == "${HOME}"* ]]; then
-    curDir="${curDir/$HOME/\~/}"
+    curDir="${curDir/$HOME/\~/}" #replace $HOME with '~'
   fi
+  
+  #adjust printed dir based on term width 
+  local term_width=$((`tput cols`-1))
+  local pre_line="  ╭ 00:00xx  ${HOSTNAME}@${USER}  --> "
+  local pre_len=${#pre_line}
+  #length of full first line
   local total_len=$((${#curDir}+${pre_len}))
   if [[ ${total_len} -gt ${term_width} ]]; then
     local pre_len_diff=$((term_width-pre_len))
     if [[ ${pre_len_diff} -lt 5 ]]; then
-      :
-    else
+      : #too lazy to fix this, I don't plan to use a terminal this narrow
+    else #cut-off string and add '...' to beginning 
       curDir=${curDir: -$((pre_len_diff-3))}
       curDir="...${curDir}"
     fi
   fi
+
+  #build $PS1
   PS1+="\n  "
   PS1+="\[${cyan}\]╭\[${reset}\]"
   PS1+="\[${BG_GRAY}${white}\] ${timeStamp} \[${reset}\] "
@@ -168,10 +180,11 @@ __mkps1() {
   PS1+="@\[${reset}${cyan}\]\u\[${reset}\]"
   PS1+=" \[${bold}${red}\]-->\[${reset}\] "
   PS1+="\[${bold}${cyan}\]${curDir}\[${reset}\]"
-  PS1+="\n  "
+  PS1+="\n  " #start second line
   PS1+="\[${cyan}\]╰\[${reset}\]"
   PS1+="\[${bold}${prompt_color}\]\$\[${reset}\] "
-  true
+
+  true #attempt at reseting $? (doesn't work)
 }
 
 
@@ -189,21 +202,22 @@ alias goNoCache="GOPROXY=direct go"
 alias laR="eza -aR"
 alias CURDIR="basename \"${PWD}\""
 
+
 ############################
 #     ever-so-slightly     #
 #   more complex aliases   #
 ############################
+#get just ipv4 of tailscale machine
 getTail() {
   tailscale ip "${1}" | sed -n "1p"
-}
+} #cd into dir then eza
 cdls() {
   cd "$1"
   eza ${@:2}
-}
+} #mkdir then cd into it
 mkcd() {
   mkdir "${1}"
   cd "${1}"
-  eza ${@:2}
 }
 
 
@@ -217,22 +231,25 @@ PATH=$PATH:/home/super/.local/share/gem/ruby/3.3.0/bin
 PATH=$PATH:/home/super/.local/bin
 
 
+#############################
+#      custom  exports      #
+#############################
 #vitasdk (PS Vita homebew)
 export VITASDK=/usr/local/vitasdk
 export PATH=$VITASDK/bin:$PATH
-
 # bun
 export BUN_INSTALL="$HOME/.bun"
 export PATH="$BUN_INSTALL/bin:$PATH"
+# make neovim the default
+export EDITOR='/usr/bin/nvim'
+export VISUAL='/usr/bin/nvim'
+
 
 #############################
 #       NeoVim  stuff       #
 #############################
 export NVM_DIR="$HOME/.nvm"
 # This loads nvm
-[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
 # This loads nvm bash_completion
-[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  
-#  make neovim the default
-export EDITOR='/usr/bin/nvim'
-export VISUAL='/usr/bin/nvim'
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
